server:
  port: 8080

spring:
  application:
    name: api-gateway
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoReactiveDataAutoConfiguration
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**

        - id: stock-service
          uri: lb://STOCK-SERVICE
          predicates:
            - Path=/api/stock/**

        - id: venta-service
          uri: lb://VENTA-SERVICE
          predicates:
            - Path=/api/ventas/**

        - id: despacho-service
          uri: lb://DESPACHO-SERVICE
          predicates:
            - Path=/api/despachos/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

  main:
    web-application-type: reactive

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

logging:
  level:
    org.springframework.cloud.gateway: INFO
