server:
  port: 8761

spring:
  application:
    name: eureka-server
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoReactiveDataAutoConfiguration
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      dynatrace:
        enabled: ${DYNATRACE_ENABLED:false}
        uri: ${DYNATRACE_URI:}
        api-token: ${DYNATRACE_API_TOKEN:}
        v2:
          metric-key-prefix: pos
          enrich-with-dynatrace-metadata: true
    tags:
      application: pos-system
      service: eureka-server